title: Tahjib Ahmed S.
logo: /assets/img/headshot_circle.png
description: Entry-level Data Analyst . BI Analyst . Business analyst . Power Bi specialist
show_downloads: true
theme: jekyll-theme-minimal
