title: Tahjib Ahmed S.
logo: /assets/img/tahjib.jpg
description: Entry-level Data Analyst . BI Analyst . Power BI specialist
show_downloads: true
theme: jekyll-theme-minimal

# Additional Customization
favicon: /assets/img/favicon.ico # Add a favicon if you want
social:
  twitter: your-twitter-handle
  linkedin: your-linkedin-handle
  github: your-github-handle
