title: "Tahjib Ahmed S."
description: "Freelance Data Analyst · BI Analyst · Power BI Specialist"
baseurl: "" # leave empty for GitHub Pages
url: "https://tahjib07.github.io"

# IMPORTANT: This disables default theme so remote_theme works
theme: null
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

author:
  name   : "Tahjib Ahmed Siddique"
  avatar : "/assets/img/tahjib.jpg"
  bio    : "Turning data into insights using any technology needed."

social:
  links:
    - https://linkedin.com/in/tahjib07
    - https://github.com/tahjib07

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

include:
  - _pages

collections:
  pages:
    output: true
