title: Tahjib Ahmed S.
logo: /assets/img/tahjib.jpg
description: Entry-level Data Analyst . BI Analyst . Power BI specialist
show_downloads: true
theme: jekyll-theme-cayman

social:
  linkedin: www.linkedin.com/in/tahjib07
  github: https://github.com/tahjib07
