title: "Tahjib Ahmed S."
description: "Freelance Data Analyst · BI Analyst · Power BI Specialist"
baseurl: ""
url: "https://tahjib07.github.io"
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

author:
  name   : "Tahjib Ahmed Siddique"
  avatar : "/assets/img/tahjib.jpg"
  bio    : "Turning data into insights using any technology needed."

social:
  links:
    - https://linkedin.com/in/tahjib07
    - https://github.com/tahjib07

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

include:
  - _pages

collections:
  pages:
    output: true
